"""RAG vector memory for Maxwell Bot.

Replaces the old MemoryManager (memory.py) and ContextCleanupEngine
(context_cleanup.py) with a single SQLite + numpy vector store backed by
qwen3-embedding:0.6b via ollama.

Architecture:
  - SQLite database at data/maxwell_rag.db
  - Three logical stores in one table: channel messages, long-term facts,
    shared context entries — distinguished by `kind`
  - Each row stores the text, metadata JSON, and a 1024-dim embedding BLOB
  - Retrieval: cosine similarity via numpy dot product against the query
    embedding, filtered by kind/channel/scope as needed
  - Embeddings generated by POSTing to ollama's /api/embed endpoint

The public interface mirrors the old MemoryManager so bot.py changes are
minimal — same method names, same return shapes.
"""

import asyncio
import json
import logging
import sqlite3
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path

import aiohttp
import numpy as np

logger = logging.getLogger(__name__)

# ─── constants ────────────────────────────────────────────────────────

# Embedding model. qwen3-embedding:0.6b wins on context length (32k
# tokens ≈ 128k chars, vs bge-m3's 8k). For memory use case — whole
# conversations, not single sentences — the long context is the
# deciding factor; we can skip a chunking pipeline entirely. 1024-dim
# output. ollama pull qwen3-embedding:0.6b
EMBED_MODEL = "qwen3-embedding:0.6b"
EMBED_DIM = 1024
OLLAMA_EMBED_URL = "http://localhost:11434/api/embed"

# Recency decay (seconds). 14 days. Score multiplied by exp(-age/tau).
RECENCY_TAU_SECONDS = 14 * 86400.0

MAX_CHANNELS = 25
MAX_MEMORY_CHARS = 1000
MAX_LTM_LINES = 999
DEFAULT_REM_EVENT_BUFFER_MAX = 500

# Cosine similarity threshold for RAG retrieval. Below this, results are
# considered noise and filtered out.
SIM_THRESHOLD = 0.35

# ─── filtering ────────────────────────────────────────────────────────

# Discord.MessageType values that produce no real user content. We never
# embed these — they're webhook metadata, presence events, or system
# messages. Names match `discord.MessageType` enum members.
_DISCORD_SKIP_TYPES = frozenset(
    {
        "default",  # included so unset types are still allowed
        "recipient_add",
        "recipient_remove",
        "call",
        "channel_name_change",
        "channel_icon_change",
        "pins_add",
        "new_member",
        "premium_guild_subscription",
        "premium_tier",
        "channel_follow_add",
        "guild_discovery_disqualified",
        "guild_discovery_requalified",
        "guild_discovery_grace_period_initial_warning",
        "guild_discovery_grace_period_final_warning",
        "thread_created",
        "reply",  # bare reply with no other content is just metadata
        "application_command",
        "invite",
        "contextual_command",
        "forum_thread_created",
    }
)

# Phrases that signal a bot's own output got re-fed into the store. We
# flag content containing these so add_to_channel_memory can split
# source='bot' vs source='user'.
_BOT_OUTPUT_MARKERS = (
    "bold of you to assume",
    "Called send_message with",
    "Called send_dm with",
    "Called edit_message with",
    "Called run_tool with",
    "Called autodelete with",
    "Called webfetch with",
    "RAG relevance:",
)

# Monosyllable / reaction threshold. Content shorter than this (after
# stripping URLs/markdown/mentions) is too low-signal to embed. We still
# *store* it (so /api/rag/messages shows recent), we just don't embed.
_MIN_EMBED_LEN = 4

# ─── helpers ──────────────────────────────────────────────────────────


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _utcnow_iso() -> str:
    return _utcnow().isoformat()


def _parse_iso(ts: str) -> datetime | None:
    if not ts:
        return None
    try:
        dt = datetime.fromisoformat(str(ts))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    except Exception:
        return None


def _normalize_ltm_line(content: str) -> str:
    return " ".join(str(content).split())[:MAX_MEMORY_CHARS]


def _strip_reasoning_text(content: str) -> str:
    import re

    text = str(content or "")
    text = re.sub(
        r"<think\b[^>]*>.*?</think>", "", text, flags=re.IGNORECASE | re.DOTALL
    )
    return " ".join(text.split())


def _embedding_to_blob(vec: np.ndarray) -> bytes:
    """Store float32 embedding as compact BLOB."""
    return vec.astype(np.float32).tobytes()


def _blob_to_embedding(blob: bytes) -> np.ndarray:
    """Unpack BLOB back to float32 numpy array."""
    return np.frombuffer(blob, dtype=np.float32)


# ─── content filtering ────────────────────────────────────────────────


def _strip_for_embedding(text: str) -> str:
    """Normalize text before deciding 'is this worth embedding?'.

    - Strip URLs (they're not semantically meaningful by themselves)
    - Strip mentions (the bot already knows who they refer to in context)
    - Strip emojis-only runs (zero signal for recall)
    - Collapse whitespace

    Returns the cleaned string. Length of *this* decides embed vs skip.
    """
    import re

    s = str(text or "")
    if not s:
        return ""
    s = re.sub(r"https?://\S+", " ", s)
    s = re.sub(r"<@!?\d+>", " ", s)
    s = re.sub(r"<#\d+>", " ", s)
    s = re.sub(r":[a-zA-Z0-9_]+:", " ", s)  # emoji shortcodes
    s = re.sub(r"[\U00010000-\U0010ffff]", " ", s)  # unicode emoji
    s = re.sub(r"\s+", " ", s).strip()
    return s


def _is_system_event_content(content: str, message_type: str | None = None) -> bool:
    """True if this content is a Discord system event, not a user message.

    Detects embeds like `[embeds: Avatar update]` or `[embeds: Member left]`
    that the bot renders when no real message text exists.
    """
    if message_type and str(message_type) in _DISCORD_SKIP_TYPES:
        return True
    s = str(content or "").strip()
    if not s:
        return True
    if s.startswith("[embeds:") and s.endswith("]"):
        return True
    if s.startswith("[Message deleted in"):
        return True
    return False


def _detect_source(message: dict) -> str:
    """Figure out source='user' | 'bot' | 'system' for a message dict.

    Priority order:
    1. Explicit `source` field wins
    2. `author_is_bot: True` → 'bot'
    3. `_BOT_OUTPUT_MARKERS` substring match → 'bot'
    4. `_is_system_event_content` → 'system'
    5. Default 'user'
    """
    src = message.get("source")
    if src in ("user", "bot", "system"):
        return src
    if message.get("author_is_bot") is True:
        return "bot"
    content = str(message.get("content") or "")
    for marker in _BOT_OUTPUT_MARKERS:
        if marker in content:
            return "bot"
    if _is_system_event_content(content, message.get("message_type")):
        return "system"
    return "user"


def _score_with_recency(
    cosine: float, ts: str | None, now_ts: float | None = None
) -> float:
    """Apply recency decay: cosine * exp(-age_seconds / τ).

    LTM and shared_context always score at full cosine (they're durable
    facts by definition — their timestamp is when they were *written*,
    not when the underlying event happened). Pass kind='message' to opt
    out.
    """
    if not ts:
        return float(cosine)
    dt = _parse_iso(ts)
    if dt is None:
        return float(cosine)
    if now_ts is None:
        now_ts = _utcnow().timestamp()
    age = max(0.0, float(now_ts) - dt.timestamp())
    import math

    decay = math.exp(-age / RECENCY_TAU_SECONDS)
    return float(cosine) * (0.25 + 0.75 * decay)  # never below 25% of raw cosine


# ─── RemEventLog (kept identical — REM still uses it) ────────────────


class RemEventLog:
    """JSON-backed visible event ring for REM assimilation."""

    def __init__(self, data_dir: str, max_events: int = DEFAULT_REM_EVENT_BUFFER_MAX):
        self.data_dir = Path(data_dir)
        self.events_file = self.data_dir / "rem_events.json"
        self.max_events = max(1, int(max_events or DEFAULT_REM_EVENT_BUFFER_MAX))
        self.events = []
        self._lock = asyncio.Lock()
        self._dirty = False
        self._save_task = None
        self._pending_save = None
        self._save_lock = asyncio.Lock()

    def load_from_disk(self):
        try:
            if self.events_file.exists():
                data = json.loads(self.events_file.read_text(encoding="utf-8"))
                self.events = self._sanitize_events(
                    data if isinstance(data, list) else []
                )
        except (json.JSONDecodeError, OSError) as e:
            logger.error(f"Failed to load REM events: {e}")
            self.events = []

    def _sanitize_events(self, events: list) -> list:
        clean = []
        for raw in events:
            if not isinstance(raw, dict):
                continue
            role = str(raw.get("role") or "")
            if role not in {"user", "assistant"}:
                # Also accept events with kind/timestamp format (used by bot.py)
                if not raw.get("kind") and not raw.get("timestamp"):
                    continue
                # Convert kind-based events to the expected format
                role = str(raw.get("kind") or "user")
            mentions = []
            for row in list(raw.get("mentions") or [])[:10]:
                if not isinstance(row, dict):
                    continue
                mid = str(row.get("id") or "")
                if not mid:
                    continue
                mentions.append({"id": mid, "name": str(row.get("name") or mid)[:120]})
            clean.append(
                {
                    "ts": str(raw.get("ts") or raw.get("timestamp") or _utcnow_iso()),
                    "channel_id": str(raw.get("channel_id") or ""),
                    "guild_id": str(raw.get("guild_id"))
                    if raw.get("guild_id") is not None
                    else None,
                    "message_id": str(raw.get("message_id") or ""),
                    "user_id": str(raw.get("user_id") or ""),
                    "user_name": str(raw.get("user_name") or "")[:120],
                    "role": role,
                    "content": _strip_reasoning_text(raw.get("content", ""))[:4000],
                    "mentions": mentions,
                    "reply_to_message_id": str(raw.get("reply_to_message_id") or ""),
                    "reply_to_author": str(raw.get("reply_to_author") or "")[:120],
                    "reply_to_author_id": str(raw.get("reply_to_author_id") or ""),
                    "reply_to_self": bool(raw.get("reply_to_self", False)),
                    "auto_mode": bool(raw.get("auto_mode", False)),
                    "id": str(raw.get("id") or ""),
                    "kind": str(raw.get("kind") or role),
                    "timestamp": str(raw.get("timestamp") or _utcnow_iso()),
                }
            )
        return clean[-self.max_events :]

    async def _atomic_save(self, snapshot: list):
        async with self._save_lock:
            from utils import _atomic_json_write_sync

            await asyncio.to_thread(_atomic_json_write_sync, self.events_file, snapshot)

    def _schedule_save(self):
        self._dirty = True
        if self._save_task is not None:
            self._save_task.cancel()
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            return

        async def _debounced():
            try:
                await asyncio.sleep(5)
                await self._do_save()
            except asyncio.CancelledError:
                pass

        self._save_task = loop.create_task(_debounced())

    async def _do_save(self):
        self._save_task = None
        if self._dirty:
            self._dirty = False
            snapshot = list(self.events)
            await self._atomic_save(snapshot)

    async def record(self, event: dict):
        async with self._lock:
            # Sanitize through _sanitize_events to get consistent format
            clean = self._sanitize_events([event])
            if not clean or not clean[0]["content"]:
                return
            self.events.append(clean[0])
            if len(self.events) > self.max_events:
                self.events = self.events[-self.max_events :]
            self._schedule_save()

    async def drain_slice(self, since_ts: str | None = None) -> list:
        since = _parse_iso(since_ts or "")
        async with self._lock:
            if since is None:
                return [dict(e) for e in self.events]
            out = []
            for event in self.events:
                ts = _parse_iso(event.get("ts", event.get("timestamp", "")))
                if ts and ts > since:
                    out.append(dict(event))
            return out

    async def size(self) -> int:
        async with self._lock:
            return len(self.events)

    async def flush(self):
        async with self._lock:
            if self._save_task:
                self._save_task.cancel()
                self._save_task = None
            self._dirty = True
            await self._do_save()


# ─── RAGMemoryManager ────────────────────────────────────────────────


class RAGMemoryManager:
    """Vector-backed memory manager. Drop-in replacement for MemoryManager.

    Stores channel messages, long-term facts, and shared context entries
    in a single SQLite table with embeddings. Retrieval uses cosine
    similarity for semantic search (RAG).

    Public interface matches the old MemoryManager:
      - get_channel_memory(channel_id) -> list[dict]
      - add_to_channel_memory(channel_id, message) -> None
      - clear_channel_memory(channel_id) -> None
      - get_long_term_memory() -> list[dict]
      - add_long_term_memory(content) -> str
      - edit_long_term_memory(memory_id, content) -> bool
      - remove_long_term_memory(memory_id) -> bool
      - apply_ltm_batch(ops) -> dict
      - get_server_prompt(server_id) -> str | None
      - set_server_prompt(server_id, prompt) -> None
      - clear_server_prompt(server_id) -> None
      - add_shared_context(entry) -> str
      - remove_shared_context(context_id) -> bool
      - update_shared_context(context_id, updates) -> bool
      - list_shared_context(limit) -> list
      - get_relevant_shared_context(...) -> list

    New RAG-specific methods:
      - rag_search(query, kinds, channel_id, top_k) -> list[dict]
      - rag_relevant_context(query, channel_id, top_k) -> list[dict]
    """

    def __init__(self, data_dir: str, max_messages: int = 10000):
        self.data_dir = Path(data_dir)
        self.max_messages = min(max_messages, 10000)
        self.db_path = self.data_dir / "maxwell_rag.db"
        self.prompts_file = self.data_dir / "prompts.json"
        self._db: sqlite3.Connection | None = None
        self._lock = asyncio.Lock()
        self._embed_semaphore = asyncio.Semaphore(4)  # limit concurrent embed calls
        # Self-tuning cache state (kept minimal; SQLite holds the real cache)
        self._embed_cache: dict[
            str, np.ndarray
        ] = {}  # in-process LRU; SQLite is durable
        self._prompts: dict[str, str] = {}
        # Track background embed tasks so shutdown can await them (otherwise
        # in-flight embeds are silently dropped and rows stay embedding=NULL)
        # and so tests don't spam "coroutine ignored GeneratorExit".
        self._embed_tasks: set[asyncio.Task] = set()
        self._init_db()

    def _spawn(self, coro) -> asyncio.Task:
        """Create a tracked background task for embed work."""
        task = asyncio.ensure_future(coro)
        self._embed_tasks.add(task)
        task.add_done_callback(self._embed_tasks.discard)
        return task

    def _init_db(self):
        """Create SQLite DB and tables."""
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self._db = sqlite3.connect(
            str(self.db_path),
            check_same_thread=False,
            isolation_level=None,  # autocommit
        )
        self._db.row_factory = sqlite3.Row
        self._db.execute("PRAGMA journal_mode=WAL")
        self._db.execute("PRAGMA synchronous=NORMAL")
        self._db.execute("PRAGMA cache_size=-64000")  # 64MB cache

        self._db.execute(
            """
            CREATE TABLE IF NOT EXISTS vectors (
                id TEXT PRIMARY KEY,
                kind TEXT NOT NULL,           -- 'message', 'ltm', 'shared_context',
                                              -- 'bot_output', 'negative'
                channel_id TEXT DEFAULT '',
                guild_id TEXT DEFAULT '',     -- NEW: server/channel isolation
                author TEXT DEFAULT '',
                author_id TEXT DEFAULT '',
                source TEXT DEFAULT 'user',   -- NEW: 'user' | 'bot' | 'system'
                content TEXT NOT NULL,
                content_hash TEXT DEFAULT '', -- NEW: SHA-256 of normalized content
                embedding BLOB,
                metadata TEXT DEFAULT '{}',
                scope TEXT DEFAULT '',
                importance INTEGER DEFAULT 0,
                parent_id TEXT DEFAULT '',    -- NEW: chunks point at parent msg
                chunk_index INTEGER DEFAULT 0,-- NEW: 0 for non-chunks
                downvotes INTEGER DEFAULT 0,  -- NEW: negative-feedback counter
                timestamp TEXT NOT NULL,
                created_at REAL NOT NULL
            )
            """
        )
        # ─── in-place migration from previous schema (idempotent) ─────
        # If columns don't exist yet, ALTER TABLE … ADD COLUMN. SQLite
        # refuses duplicates, so wrap each in a try and ignore OperationalError.
        _migrations = [
            ("guild_id", "TEXT DEFAULT ''"),
            ("source", "TEXT DEFAULT 'user'"),
            ("content_hash", "TEXT DEFAULT ''"),
            ("parent_id", "TEXT DEFAULT ''"),
            ("chunk_index", "INTEGER DEFAULT 0"),
            ("downvotes", "INTEGER DEFAULT 0"),
        ]
        for col, decl in _migrations:
            try:
                self._db.execute(f"ALTER TABLE vectors ADD COLUMN {col} {decl}")
            except Exception:
                pass  # column already exists

        # Backfill content_hash from content for existing rows.
        import hashlib as _hashlib

        for r in self._db.execute(
            "SELECT id, content FROM vectors WHERE content_hash='' OR content_hash IS NULL"
        ).fetchall():
            normalized = _strip_for_embedding(r["content"])
            h = _hashlib.sha256(normalized.encode("utf-8")).hexdigest()
            self._db.execute(
                "UPDATE vectors SET content_hash=? WHERE id=?", (h, r["id"])
            )

        # Seed embed_cache from existing rows so the first recall after
        # upgrade doesn't pay 619 cold ollama calls. Cheap (we already
        # have the blobs in `vectors.embedding`).
        for r in self._db.execute(
            "SELECT content, embedding FROM vectors WHERE embedding IS NOT NULL"
        ).fetchall():
            try:
                key = _hashlib.md5(r["content"].encode()).hexdigest()
                self._db.execute(
                    "INSERT OR IGNORE INTO embed_cache "
                    "(key, dim, embedding, created_at, last_used_at, hits) "
                    "VALUES (?, ?, ?, ?, 0, 0)",
                    (key, EMBED_DIM, r["embedding"], time.time()),
                )
            except Exception:
                pass

        # Backfill source for existing rows using the same heuristic
        # the new insert path uses.
        for r in self._db.execute(
            "SELECT id, kind, content, metadata FROM vectors "
            "WHERE source='user' OR source IS NULL OR source=''"
        ).fetchall():
            try:
                meta = json.loads(r["metadata"] or "{}")
            except Exception:
                meta = {}
            author_is_bot = meta.get("author_is_bot")
            content = r["content"]
            # Bot rows were inserted with a row.id prefix 'bot_*'
            new_src = "user"
            if str(r["id"]).startswith("bot_") or r["kind"] == "bot_output":
                new_src = "bot"
            elif _is_system_event_content(content):
                new_src = "system"
            elif author_is_bot is True:
                new_src = "bot"
            else:
                for marker in _BOT_OUTPUT_MARKERS:
                    if marker in content:
                        new_src = "bot"
                        break
            self._db.execute(
                "UPDATE vectors SET source=? WHERE id=?", (new_src, r["id"])
            )

        self._db.execute("CREATE INDEX IF NOT EXISTS idx_kind ON vectors(kind)")
        self._db.execute(
            "CREATE INDEX IF NOT EXISTS idx_channel ON vectors(channel_id)"
        )
        self._db.execute(
            "CREATE INDEX IF NOT EXISTS idx_kind_channel ON vectors(kind, channel_id)"
        )
        self._db.execute(
            "CREATE INDEX IF NOT EXISTS idx_timestamp ON vectors(timestamp)"
        )
        # NEW indices for the new retrieval paths
        self._db.execute("CREATE INDEX IF NOT EXISTS idx_guild ON vectors(guild_id)")
        self._db.execute("CREATE INDEX IF NOT EXISTS idx_source ON vectors(source)")
        self._db.execute(
            "CREATE INDEX IF NOT EXISTS idx_content_hash ON vectors(content_hash)"
        )
        self._db.execute("CREATE INDEX IF NOT EXISTS idx_parent ON vectors(parent_id)")
        # Unique constraint prevents duplicate (same channel + same content).
        # Skipped rows via OR IGNORE in insert path.
        try:
            self._db.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_content "
                "ON vectors(channel_id, content_hash) WHERE content_hash != ''"
            )
        except Exception:
            pass

        # ─── persistent embedding cache ────────────────────────────────
        # Survives restart. Indexed on (key, dim) for O(log n) point lookups.
        # Text inputs are normalized before hashing (strip whitespace) so
        # the same content embedded twice hits the same cache slot.
        self._db.execute(
            """
            CREATE TABLE IF NOT EXISTS embed_cache (
                key TEXT NOT NULL,
                dim INTEGER NOT NULL,
                embedding BLOB NOT NULL,
                created_at REAL NOT NULL,
                last_used_at REAL NOT NULL,
                hits INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (key, dim)
            )
            """
        )
        self._db.execute(
            "CREATE INDEX IF NOT EXISTS idx_embed_cache_used "
            "ON embed_cache(last_used_at)"
        )

        # FTS5/BM25 hybrid search was prototyped but caused DB corruption
        # under concurrent writes (triggers + per-message embedding tasks
        # racing). Removed in favor of pure-cosine retrieval with cache.
        # The pure-cosine path is fast enough (~5ms with cached embed)
        # and correct enough for the current corpus size.

        # Migrate prompts
        try:
            if self.prompts_file.exists():
                data = json.loads(self.prompts_file.read_text(encoding="utf-8"))
                if isinstance(data, dict):
                    self._prompts = {str(k): str(v) for k, v in data.items()}
        except Exception as e:
            logger.warning(f"Failed to load prompts: {e}")
            self._prompts = {}

        # Migrate existing long_term_memory.txt if present
        self._migrate_ltm()
        # Migrate existing shared_context.json if present
        self._migrate_shared_context()

        logger.info(
            f"RAGMemoryManager initialized at {self.db_path} "
            f"({self._count_all()} vectors)"
        )

    def _count_all(self) -> int:
        try:
            row = self._db.execute("SELECT COUNT(*) as c FROM vectors").fetchone()
            return row["c"] if row else 0
        except Exception:
            return 0

    def _migrate_ltm(self):
        """One-time migration of long_term_memory.txt into the vector DB."""
        ltm_file = self.data_dir / "long_term_memory.txt"
        if not ltm_file.exists():
            return
        # Check if we already migrated (any LTM rows exist)
        try:
            row = self._db.execute(
                "SELECT COUNT(*) as c FROM vectors WHERE kind='ltm'"
            ).fetchone()
            if row and row["c"] > 0:
                return  # already migrated
        except Exception:
            pass

        try:
            lines = ltm_file.read_text(encoding="utf-8").strip().splitlines()
            migrated = 0
            import hashlib as _hashlib

            for line in lines:
                line = line.strip()
                if not line:
                    continue
                # Try to parse old format: "content|timestamp|id" or just "content"
                parts = line.split("|")
                content = parts[0].strip() if parts else line
                ts = parts[1].strip() if len(parts) > 1 else _utcnow_iso()
                mid = parts[2].strip() if len(parts) > 2 else uuid.uuid4().hex

                norm = _strip_for_embedding(content)
                ch = _hashlib.sha256(norm.encode("utf-8")).hexdigest()

                # Insert without embedding first (will be embedded lazily on search)
                self._db.execute(
                    "INSERT OR IGNORE INTO vectors (id, kind, channel_id, guild_id, "
                    "author, author_id, source, content, content_hash, embedding, "
                    "metadata, scope, importance, parent_id, chunk_index, downvotes, "
                    "timestamp, created_at) "
                    "VALUES (?, 'ltm', '', '', '', '', 'user', ?, ?, NULL, '{}', "
                    "'global', 5, '', 0, 0, ?, ?)",
                    (mid, content[:MAX_MEMORY_CHARS], ch, ts, time.time()),
                )
                migrated += 1
            if migrated:
                logger.info(f"Migrated {migrated} LTM lines from long_term_memory.txt")
                # Embed them in background
                self._spawn(self._embed_pending("ltm"))
        except Exception as e:
            logger.warning(f"LTM migration failed: {e}")

    def _migrate_shared_context(self):
        """One-time migration of shared_context.json into the vector DB."""
        sc_file = self.data_dir / "shared_context.json"
        if not sc_file.exists():
            return
        try:
            row = self._db.execute(
                "SELECT COUNT(*) as c FROM vectors WHERE kind='shared_context'"
            ).fetchone()
            if row and row["c"] > 0:
                return  # already migrated
        except Exception:
            pass

        try:
            data = json.loads(sc_file.read_text(encoding="utf-8"))
            if not isinstance(data, list):
                return
            migrated = 0
            for entry in data:
                if not isinstance(entry, dict):
                    continue
                cid = str(entry.get("id") or uuid.uuid4().hex)
                content = str(entry.get("content") or "")[:1200]
                scope = str(entry.get("scope") or "global")
                importance = int(entry.get("importance") or 5)
                ts = str(entry.get("timestamp") or _utcnow_iso())
                metadata = json.dumps(
                    {
                        k: v
                        for k, v in entry.items()
                        if k
                        not in ("id", "content", "scope", "importance", "timestamp")
                    }
                )
                self._db.execute(
                    "INSERT OR IGNORE INTO vectors (id, kind, channel_id, author, author_id, content, embedding, metadata, scope, importance, timestamp, created_at) VALUES (?, 'shared_context', '', '', '', ?, NULL, ?, ?, ?, ?, ?)",
                    (cid, content, metadata, scope, importance, ts, time.time()),
                )
                migrated += 1
            if migrated:
                logger.info(f"Migrated {migrated} shared context entries")
                self._spawn(self._embed_pending("shared_context"))
        except Exception as e:
            logger.warning(f"Shared context migration failed: {e}")

    # ─── embedding ──────────────────────────────────────────────────

    async def _embed(self, text: str) -> np.ndarray | None:
        """Generate embedding via ollama, cached on disk to SQLite.

        Cache key is md5(normalized_text). The cache survives bot
        restarts and is shared across processes (admin API, one-off
        scripts) since it lives in the same SQLite db.

        Cold call: ~138ms (ollama warmup).
        Cache hit: ~0.5ms (SQLite SELECT).
        """
        text = str(text or "").strip()
        if not text:
            return None
        # Truncate very long text before embedding
        if len(text) > 8000:
            text = text[:8000]

        import hashlib

        cache_key = hashlib.md5(text.encode()).hexdigest()

        # ─── disk cache hit ─────────────────────────────────────────
        try:
            cached = self._db.execute(
                "SELECT embedding FROM embed_cache WHERE key=? AND dim=?",
                (cache_key, EMBED_DIM),
            ).fetchone()
            if cached and cached["embedding"]:
                vec = _blob_to_embedding(cached["embedding"])
                if len(vec) == EMBED_DIM:
                    # Bump last_used_at + hits so LRU keeps useful entries.
                    try:
                        self._db.execute(
                            "UPDATE embed_cache SET last_used_at=?, hits=hits+1 "
                            "WHERE key=? AND dim=?",
                            (time.time(), cache_key, EMBED_DIM),
                        )
                    except Exception:
                        pass
                    return vec
        except Exception:
            pass

        payload = {"model": EMBED_MODEL, "input": text}

        try:
            async with self._embed_semaphore:
                async with aiohttp.ClientSession() as session:
                    async with session.post(
                        OLLAMA_EMBED_URL,
                        json=payload,
                        timeout=aiohttp.ClientTimeout(total=30),
                    ) as resp:
                        if resp.status != 200:
                            body = await resp.text()
                            logger.warning(
                                f"Embedding API returned {resp.status}: {body[:200]}"
                            )
                            return None
                        data = await resp.json()
                        embeddings = data.get("embeddings") or []
                        if not embeddings:
                            emb = data.get("embedding")
                            if emb:
                                embeddings = [emb]
                        if not embeddings:
                            logger.warning("Embedding API returned no embeddings")
                            return None
                        vec = np.array(embeddings[0], dtype=np.float32)
                        if len(vec) != EMBED_DIM:
                            logger.warning(
                                f"Embedding dimension mismatch: {len(vec)} != {EMBED_DIM}"
                            )
                            return None

                        # ─── persist to cache ─────────────────────
                        try:
                            self._db.execute(
                                "INSERT OR REPLACE INTO embed_cache "
                                "(key, dim, embedding, created_at, last_used_at, hits) "
                                "VALUES (?, ?, ?, ?, ?, COALESCE("
                                "  (SELECT hits FROM embed_cache WHERE key=? AND dim=?),"
                                "  0) + 1)",
                                (
                                    cache_key,
                                    EMBED_DIM,
                                    _embedding_to_blob(vec),
                                    time.time(),
                                    time.time(),
                                    cache_key,
                                    EMBED_DIM,
                                ),
                            )
                            self._maybe_prune_embed_cache()
                        except Exception:
                            pass  # cache write failure is non-fatal

                        return vec
        except asyncio.TimeoutError:
            logger.warning("Embedding API timeout")
            return None
        except Exception as e:
            logger.warning(f"Embedding failed: {e}")
            return None

    def _maybe_prune_embed_cache(self):
        """Cap the on-disk embed cache at 10k entries by LRU eviction.

        Rate-limited to once per 60s via `_last_embed_cache_prune` so
        heavy traffic doesn't slam SQLite with DELETE sweeps.
        """
        try:
            now = time.time()
            if getattr(self, "_last_embed_cache_prune", 0.0) + 60 > now:
                return
            self._last_embed_cache_prune = now

            cap = 10000
            cur = self._db.execute("SELECT COUNT(*) as c FROM embed_cache").fetchone()
            n = cur["c"] if cur else 0
            if n <= cap:
                return

            excess = n - cap
            self._db.execute(
                "DELETE FROM embed_cache WHERE key IN ("
                "SELECT key FROM embed_cache ORDER BY last_used_at ASC "
                "LIMIT ?)",
                (excess,),
            )
        except Exception:
            pass

    async def _embed_and_store(self, row_id: str, text: str):
        """Generate embedding and update the row in DB."""
        vec = await self._embed(text)
        if vec is not None:
            blob = _embedding_to_blob(vec)
            self._db.execute(
                "UPDATE vectors SET embedding=? WHERE id=?",
                (blob, row_id),
            )

    async def _embed_pending(self, kind: str):
        """Embed all rows of a kind that don't have embeddings yet."""
        try:
            rows = self._db.execute(
                "SELECT id, content FROM vectors WHERE kind=? AND embedding IS NULL",
                (kind,),
            ).fetchall()
            for row in rows:
                await self._embed_and_store(row["id"], row["content"])
            if rows:
                logger.info(f"Embedded {len(rows)} pending {kind} vectors")
        except Exception as e:
            logger.warning(f"Failed to embed pending {kind}: {e}")

    async def _embed_pending_all(self, batch_size: int = 50):
        """Embed ALL rows without embeddings, in batches. Used for migration.

        Uses ollama's batch embed API to speed up — sends multiple texts
        in a single request instead of one-at-a-time.
        """
        try:
            total_embedded = 0
            while True:
                rows = self._db.execute(
                    "SELECT id, content FROM vectors WHERE embedding IS NULL LIMIT ?",
                    (batch_size,),
                ).fetchall()
                if not rows:
                    break

                # Batch embed: send all texts in one request
                texts = [row["content"][:8000] for row in rows]
                payload = {"model": EMBED_MODEL, "input": texts}

                try:
                    async with self._embed_semaphore:
                        async with aiohttp.ClientSession() as session:
                            async with session.post(
                                OLLAMA_EMBED_URL,
                                json=payload,
                                timeout=aiohttp.ClientTimeout(total=120),
                            ) as resp:
                                if resp.status != 200:
                                    body = await resp.text()
                                    logger.warning(
                                        f"Batch embed API returned {resp.status}: {body[:200]}"
                                    )
                                    # Fall back to one-by-one
                                    for row in rows:
                                        await self._embed_and_store(
                                            row["id"], row["content"]
                                        )
                                        total_embedded += 1
                                    continue
                                data = await resp.json()
                                embeddings = data.get("embeddings") or []
                                if not embeddings:
                                    logger.warning("Batch embed returned no embeddings")
                                    continue
                                for i, row in enumerate(rows):
                                    if i < len(embeddings):
                                        vec = np.array(embeddings[i], dtype=np.float32)
                                        if len(vec) == EMBED_DIM:
                                            blob = _embedding_to_blob(vec)
                                            self._db.execute(
                                                "UPDATE vectors SET embedding=? WHERE id=?",
                                                (blob, row["id"]),
                                            )
                                            total_embedded += 1
                except Exception as e:
                    logger.warning(f"Batch embed failed: {e}")
                    # Fall back to one-by-one for this batch
                    for row in rows:
                        await self._embed_and_store(row["id"], row["content"])
                        total_embedded += 1

            if total_embedded:
                logger.info(f"Batch-embedded {total_embedded} vectors total")
        except Exception as e:
            logger.warning(f"Failed to embed pending vectors: {e}")

    # ─── channel memory (short-term) ──────────────────────────────

    async def get_channel_memory(self, channel_id: str) -> list[dict]:
        """Return recent messages for a channel, oldest first."""
        rows = self._db.execute(
            "SELECT id, author, author_id, content, timestamp, metadata FROM vectors WHERE kind='message' AND channel_id=? ORDER BY created_at DESC LIMIT ?",
            (str(channel_id), self.max_messages),
        ).fetchall()
        # Reverse to oldest-first, and build dict entries matching old format
        result = []
        for row in reversed(rows):
            entry = {
                "author": row["author"],
                "author_id": row["author_id"],
                "content": row["content"],
                "message_id": row["id"],
                "timestamp": row["timestamp"],
            }
            try:
                meta = json.loads(row["metadata"] or "{}")
                entry.update(meta)
            except Exception:
                pass
            result.append(entry)
        return result

    async def add_to_channel_memory(self, channel_id: str, message: dict):
        """Add a message to channel memory with embedding.

        Behavior:
          - if source='system' → SKIP entirely (don't store, don't embed)
          - if source='bot'   → store as kind='bot_output'
          - if source='user'  → store as kind='message', full embedding
          - if content stripped of URLs/mentions/emoji is < 4 chars,
            store the row but do NOT request an embedding (cheap skip)
          - dedupe by (channel_id, content_hash) — silent ignore on collision
        """
        channel_id = str(channel_id)
        msg_id = str(message.get("message_id") or uuid.uuid4().hex)
        content = str(message.get("content") or "")
        author = str(message.get("author") or "")
        author_id = str(message.get("author_id") or "")
        guild_id = str(message.get("guild_id") or "")
        ts = str(message.get("timestamp") or _utcnow_iso())

        # Detect source and drop system events before they waste a row
        source = _detect_source(message)
        if source == "system":
            logger.debug(f"Skipping system event channel={channel_id} msg={msg_id}")
            return

        # Normalize for embedding decision. We embed everything that's
        # left AFTER stripping noise, regardless of how the original
        # was formatted.
        normalized = _strip_for_embedding(content)
        if not normalized:
            # still store so /api/rag/messages has recent history visible,
            # but skip the embedding call
            should_embed = False
        else:
            should_embed = len(normalized) >= _MIN_EMBED_LEN

        import hashlib as _hashlib

        content_hash = _hashlib.sha256(normalized.encode("utf-8")).hexdigest()

        # Build metadata from extra fields. We ENRICH with structured
        # signals the embed model can't see: author (formatted as
        # "DisplayName|id"), reply context, edit count, channel name
        # from the message if present. These keywords ride into the FTS
        # index even though they don't reach the embedding input.
        meta_keys = {
            "author_is_bot",
            "mentions",
            "reply_to_message_id",
            "reply_to_author",
            "reply_to_author_id",
            "reply_to_self",
            "is_tool",
            "tool_name",
            "tool_params",
            "tool_result",
            "tool_error",
            "tool_cost",
            "channel_name",
            "guild_name",
            "edited_at",
            "pinned",
        }
        metadata = {
            k: v for k, v in message.items() if k in meta_keys and v is not None
        }
        metadata["source"] = source  # always carry source in meta
        # Include the message length bucket — short messages (< 20 chars)
        # are often reactions or low-signal chatter; long ones are bots
        # or pasted logs. Used by retrieval to weight re-ranking.
        if content:
            metadata["len_bucket"] = (
                "xs"
                if len(content) < 20
                else "s"
                if len(content) < 100
                else "m"
                if len(content) < 500
                else "l"
            )

        # Bot-vs-user kind split: bot text goes to kind='bot_output' so it
        # doesn't pollute user-message RAG results.
        kind = "bot_output" if source == "bot" else "message"

        # Dedupe by (channel_id, content_hash). If a row already exists
        # with the same hash in this channel, just refresh its source/metadata
        # and bail — no new row, no re-embed.
        existing = self._db.execute(
            "SELECT id FROM vectors WHERE channel_id=? AND content_hash=? "
            "AND id != ? LIMIT 1",
            (channel_id, content_hash, msg_id),
        ).fetchone()
        if existing:
            self._db.execute(
                "UPDATE vectors SET metadata=?, source=?, updated_at=created_at "
                "WHERE id=?",
                (json.dumps(metadata), source, existing["id"]),
            )
            return

        # Delete any prior row with this exact message_id (idempotent re-send).
        self._db.execute("DELETE FROM vectors WHERE id=?", (msg_id,))

        # Insert main row.
        self._db.execute(
            "INSERT INTO vectors "
            "(id, kind, channel_id, guild_id, author, author_id, source, content, "
            " content_hash, embedding, metadata, scope, importance, parent_id, "
            " chunk_index, downvotes, timestamp, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, '', 0, '', 0, 0, ?, ?)",
            (
                msg_id,
                kind,
                channel_id,
                guild_id,
                author,
                author_id,
                source,
                content[:8000],
                content_hash,
                json.dumps(metadata),
                ts,
                time.time(),
            ),
        )

        # Prune old messages for this channel
        count_row = self._db.execute(
            "SELECT COUNT(*) as c FROM vectors WHERE kind='message' AND channel_id=?",
            (channel_id,),
        ).fetchone()
        if count_row and count_row["c"] > self.max_messages:
            excess = count_row["c"] - self.max_messages
            self._db.execute(
                "DELETE FROM vectors WHERE id IN ("
                "SELECT id FROM vectors WHERE kind='message' AND channel_id=? "
                "ORDER BY created_at ASC LIMIT ?)",
                (channel_id, excess),
            )

        # Prune channels if too many
        chan_rows = self._db.execute(
            "SELECT channel_id, COUNT(*) as c FROM vectors "
            "WHERE kind='message' GROUP BY channel_id "
            "ORDER BY MAX(created_at) DESC"
        ).fetchall()
        if len(chan_rows) > MAX_CHANNELS:
            for row in chan_rows[MAX_CHANNELS:]:
                self._db.execute(
                    "DELETE FROM vectors WHERE kind='message' AND channel_id=?",
                    (row["channel_id"],),
                )

        # Embed the whole message in background. qwen3-embedding:0.6b's
        # 32k-token context absorbs any Discord message — no chunking.
        # Skip if content too short to be worth embedding.
        if should_embed:
            self._spawn(self._embed_and_store(msg_id, content))

    async def clear_channel_memory(self, channel_id: str):
        self._db.execute(
            "DELETE FROM vectors WHERE kind='message' AND channel_id=?",
            (str(channel_id),),
        )

    # ─── long-term memory ─────────────────────────────────────────

    def cache_stats(self) -> dict:
        """Return embed_cache stats for the dashboard."""
        try:
            cur = self._db.execute(
                "SELECT COUNT(*) as c, MIN(created_at) as oldest, "
                "MAX(last_used_at) as newest, SUM(hits) as total_hits "
                "FROM embed_cache"
            ).fetchone()
            return {
                "entries": cur["c"] or 0,
                "oldest": cur["oldest"],
                "newest_used": cur["newest"],
                "total_hits": cur["total_hits"] or 0,
            }
        except Exception:
            return {"entries": 0, "oldest": None, "newest_used": None, "total_hits": 0}

    def get_long_term_memory(self) -> list[dict]:
        """Return all LTM entries (sync, for backwards compat)."""
        rows = self._db.execute(
            "SELECT id, content, timestamp FROM vectors WHERE kind='ltm' ORDER BY created_at ASC"
        ).fetchall()
        return [
            {
                "id": row["id"],
                "content": row["content"],
                "timestamp": row["timestamp"],
            }
            for row in rows
        ]

    async def add_long_term_memory(self, content: str) -> str:
        content = _normalize_ltm_line(content)
        mid = uuid.uuid4().hex
        ts = _utcnow_iso()
        import hashlib as _hashlib

        norm = _strip_for_embedding(content)
        ch = _hashlib.sha256(norm.encode("utf-8")).hexdigest()
        self._db.execute(
            "INSERT INTO vectors (id, kind, channel_id, guild_id, author, author_id, "
            "source, content, content_hash, embedding, metadata, scope, importance, "
            "parent_id, chunk_index, downvotes, timestamp, created_at) "
            "VALUES (?, 'ltm', '', '', '', '', 'user', ?, ?, NULL, '{}', 'global', "
            "5, '', 0, 0, ?, ?)",
            (mid, content, ch, ts, time.time()),
        )
        # Prune if exceeding max
        count_row = self._db.execute(
            "SELECT COUNT(*) as c FROM vectors WHERE kind='ltm'"
        ).fetchone()
        if count_row and count_row["c"] > MAX_LTM_LINES:
            excess = count_row["c"] - MAX_LTM_LINES
            self._db.execute(
                "DELETE FROM vectors WHERE id IN (SELECT id FROM vectors WHERE kind='ltm' ORDER BY created_at ASC LIMIT ?)",
                (excess,),
            )
        # Embed in background
        self._spawn(self._embed_and_store(mid, content))
        return mid

    async def edit_long_term_memory(self, memory_id: str, content: str) -> bool:
        content = _normalize_ltm_line(content)
        import hashlib as _hashlib

        norm = _strip_for_embedding(content)
        ch = _hashlib.sha256(norm.encode("utf-8")).hexdigest()
        cursor = self._db.execute(
            "UPDATE vectors SET content=?, content_hash=?, embedding=NULL "
            "WHERE id=? AND kind='ltm'",
            (content, ch, str(memory_id)),
        )
        if cursor.rowcount > 0:
            self._spawn(self._embed_and_store(str(memory_id), content))
            return True
        return False

    async def remove_long_term_memory(self, memory_id: str) -> bool:
        cursor = self._db.execute(
            "DELETE FROM vectors WHERE id=? AND kind='ltm'", (str(memory_id),)
        )
        return cursor.rowcount > 0

    async def apply_ltm_batch(self, ops: list[dict]) -> dict:
        """Apply batch LTM operations (add/edit/delete)."""
        added = 0
        edited = 0
        deleted = 0
        errors = 0
        for op in ops:
            try:
                kind = str(op.get("kind") or op.get("op") or "")
                if kind == "add":
                    content = str(op.get("content") or "")
                    if content:
                        await self.add_long_term_memory(content)
                        added += 1
                elif kind == "edit":
                    mid = str(op.get("id") or "")
                    content = str(op.get("content") or "")
                    if mid and content:
                        if await self.edit_long_term_memory(mid, content):
                            edited += 1
                        else:
                            errors += 1
                elif kind == "delete":
                    mid = str(op.get("id") or "")
                    if mid:
                        if await self.remove_long_term_memory(mid):
                            deleted += 1
                        else:
                            errors += 1
            except Exception as e:
                logger.warning(f"LTM batch op failed: {e}")
                errors += 1
        return {"added": added, "edited": edited, "deleted": deleted, "errors": errors}

    # ─── server prompts (kept as JSON file) ───────────────────────

    def get_server_prompt(self, server_id: str) -> str | None:
        return self._prompts.get(str(server_id))

    def set_server_prompt(self, server_id: str, prompt: str):
        self._prompts[str(server_id)] = str(prompt)
        self._save_prompts()

    def clear_server_prompt(self, server_id: str):
        self._prompts.pop(str(server_id), None)
        self._save_prompts()

    def _save_prompts(self):
        try:
            from utils import _atomic_json_write_sync

            _atomic_json_write_sync(self.prompts_file, self._prompts)
        except Exception as e:
            logger.error(f"Failed to save prompts: {e}")

    # ─── shared context ───────────────────────────────────────────

    async def add_shared_context(self, entry: dict) -> str:
        cid = str(entry.get("id") or uuid.uuid4().hex)
        content = str(entry.get("content") or "")[:1200]
        scope = str(entry.get("scope") or "global")
        importance = int(entry.get("importance") or 5)
        ts = str(entry.get("timestamp") or _utcnow_iso())
        metadata = json.dumps(
            {
                k: v
                for k, v in entry.items()
                if k not in ("id", "content", "scope", "importance", "timestamp")
            }
        )
        import hashlib as _hashlib

        norm = _strip_for_embedding(content)
        ch = _hashlib.sha256(norm.encode("utf-8")).hexdigest()
        self._db.execute(
            "INSERT OR REPLACE INTO vectors (id, kind, channel_id, guild_id, author, "
            "author_id, source, content, content_hash, embedding, metadata, scope, "
            "importance, parent_id, chunk_index, downvotes, timestamp, created_at) "
            "VALUES (?, 'shared_context', '', '', '', '', 'user', ?, ?, NULL, ?, ?, ?, "
            "'', 0, 0, ?, ?)",
            (cid, content, ch, metadata, scope, importance, ts, time.time()),
        )
        self._spawn(self._embed_and_store(cid, content))
        return cid

    async def remove_shared_context(self, context_id: str) -> bool:
        cursor = self._db.execute(
            "DELETE FROM vectors WHERE id=? AND kind='shared_context'",
            (str(context_id),),
        )
        return cursor.rowcount > 0

    async def update_shared_context(self, context_id: str, updates: dict) -> bool:
        sets = []
        params = []
        for key in ("content", "scope", "importance"):
            if key in updates:
                sets.append(f"{key}=?")
                params.append(updates[key])
        if not sets:
            return False
        sets.append("embedding=NULL")  # force re-embed if content changed
        params.append(str(context_id))
        cursor = self._db.execute(
            f"UPDATE vectors SET {', '.join(sets)} WHERE id=? AND kind='shared_context'",
            params,
        )
        if cursor.rowcount > 0:
            if "content" in updates:
                self._spawn(
                    self._embed_and_store(str(context_id), str(updates["content"]))
                )
            return True
        return False

    async def list_shared_context(self, limit: int = 200) -> list[dict]:
        rows = self._db.execute(
            "SELECT id, content, scope, importance, timestamp, metadata FROM vectors WHERE kind='shared_context' ORDER BY importance DESC, created_at DESC LIMIT ?",
            (limit,),
        ).fetchall()
        result = []
        for row in rows:
            entry = {
                "id": row["id"],
                "content": row["content"],
                "scope": row["scope"],
                "importance": row["importance"],
                "timestamp": row["timestamp"],
            }
            try:
                meta = json.loads(row["metadata"] or "{}")
                entry.update(meta)
            except Exception:
                pass
            result.append(entry)
        return result

    async def get_relevant_shared_context(
        self,
        user_id: str = "",
        guild_id: str = "",
        channel_id: str = "",
        is_dm: bool = False,
        is_admin: bool = False,
        max_items: int = 10,
    ) -> list[dict]:
        """Return shared context entries relevant to the current context.

        Filters by scope (user/channel/guild/global) and returns the most
        important entries. With RAG, this could also do semantic search
        but we keep scope-based filtering for shared context since it's
        already structured.
        """
        scopes = ["global"]
        if guild_id:
            scopes.append(f"guild:{guild_id}")
        if channel_id:
            scopes.append(f"channel:{channel_id}")
        if user_id:
            scopes.append(f"user:{user_id}")
        if is_dm and user_id:
            scopes.append(f"dm:{user_id}")

        placeholders = ",".join("?" * len(scopes))
        rows = self._db.execute(
            f"SELECT id, content, scope, importance, timestamp, metadata FROM vectors WHERE kind='shared_context' AND scope IN ({placeholders}) ORDER BY importance DESC, created_at DESC LIMIT ?",
            (*scopes, max_items * 2),
        ).fetchall()

        result = []
        for row in rows:
            entry = {
                "id": row["id"],
                "content": row["content"],
                "scope": row["scope"],
                "importance": row["importance"],
                "timestamp": row["timestamp"],
            }
            try:
                meta = json.loads(row["metadata"] or "{}")
                entry.update(meta)
            except Exception:
                pass
            result.append(entry)

        # Filter DM-to-admin-only
        if not is_admin:
            result = [
                e
                for e in result
                if not str(e.get("scope", "")).startswith("dm:")
                or str(e.get("scope", "")) == f"dm:{user_id}"
            ]

        return result[:max_items]

    # ─── Tier 3: feedback + summarization ────────────────────────────

    async def downvote_recent(self, message_id: str, amount: int = 1) -> bool:
        """Mark a message as a bad RAG hit. Increments downvotes.

        High-downvote rows are multiplied down in scoring during
        rag_search via the `1.0 - 0.2 * downvotes` factor.
        """
        cursor = self._db.execute(
            "UPDATE vectors SET downvotes=downvotes+? WHERE id=?",
            (int(amount), str(message_id)),
        )
        return cursor.rowcount > 0

    async def clear_downvotes(self, message_id: str) -> bool:
        cursor = self._db.execute(
            "UPDATE vectors SET downvotes=0 WHERE id=?", (str(message_id),)
        )
        return cursor.rowcount > 0

    async def add_negative(self, content: str, reason: str = "") -> str:
        """Persist a (query, bad_response) pair as a negative example.

        Retrieval excludes any candidate within cosine ≥ 0.85 of a
        negative, so this is the bot's active learning channel for
        'don't dredge this up again'. Use with the bot's owner-control
        command from bot.py.
        """
        cid = "neg_" + uuid.uuid4().hex[:12]
        meta = {"reason": reason[:500]}
        self._db.execute(
            "INSERT INTO vectors (id, kind, channel_id, guild_id, author, "
            "author_id, source, content, content_hash, embedding, metadata, "
            "scope, importance, parent_id, chunk_index, downvotes, timestamp, "
            "created_at) "
            "VALUES (?, 'negative', '', '', 'system', 'system', 'system', "
            "?, ?, NULL, ?, '', 0, '', 0, 0, ?, ?)",
            (
                cid,
                content[:1500],
                "",
                json.dumps(meta),
                _utcnow_iso(),
                time.time(),
            ),
        )
        self._spawn(self._embed_and_store(cid, content))
        return cid

    async def list_negatives(self, limit: int = 50) -> list[dict]:
        rows = self._db.execute(
            "SELECT id, content, metadata, timestamp FROM vectors "
            "WHERE kind='negative' ORDER BY created_at DESC LIMIT ?",
            (int(limit),),
        ).fetchall()
        return [
            {
                "id": r["id"],
                "content": r["content"],
                "reason": json.loads(r["metadata"] or "{}").get("reason", ""),
                "timestamp": r["timestamp"],
            }
            for r in rows
        ]

    async def remove_negative(self, nid: str) -> bool:
        cursor = self._db.execute(
            "DELETE FROM vectors WHERE id=? AND kind='negative'", (str(nid),)
        )
        return cursor.rowcount > 0

    async def summarize_recent_to_ltm(
        self, hours: int = 24, max_facts: int = 20
    ) -> int:
        """Tier-3 auto-summarizer: turn recent message traffic into LTM
        facts via the LLM.

        Pulls every kind='message' row from the last `hours` hours across
        all channels and guilds, joins them into one transcript, asks the
        configured LLM to extract durable facts (preferences, identity
        info, technical facts, ongoing tasks), and upserts each fact as
        kind='ltm'. Dedupe by content_hash so running twice doesn't
        double-write.

        Returns the number of new LTM rows written.

        Configurable via `_ltm_summarizer_prompt` (override in subclass
        or pass explicitly); default prompt below is biased toward
        pragmatic, terse facts — not verbatim quotes.
        """
        # 1. gather recent rows
        since_dt = _utcnow()
        from datetime import timedelta as _td

        cutoff = (since_dt - _td(hours=int(hours))).isoformat()
        rows = self._db.execute(
            "SELECT id, channel_id, author, content, timestamp FROM vectors "
            "WHERE kind='message' AND source='user' AND timestamp > ? "
            "ORDER BY timestamp ASC LIMIT 500",
            (cutoff,),
        ).fetchall()
        if len(rows) < 3:
            return 0

        transcript_lines = []
        for r in rows:
            ts_short = str(r["timestamp"])[:16].replace("T", " ")
            content_short = str(r["content"])[:280].replace("\n", " ")
            transcript_lines.append(
                f"[{ts_short}] #{r['channel_id']} {r['author']}: {content_short}"
            )
        transcript = "\n".join(transcript_lines)
        if len(transcript) > 12000:
            transcript = transcript[:12000] + "\n…[truncated]"

        # 2. call the LLM
        try:
            facts = await self._call_ltm_extractor(transcript, max_facts=max_facts)
        except Exception as e:
            logger.warning(f"LTM summarizer LLM call failed: {e}")
            return 0
        if not facts:
            return 0

        # 3. upsert each fact as LTM, dedupe by content_hash
        import hashlib as _hashlib

        added = 0
        for fact in facts:
            fact = str(fact or "").strip()
            if len(fact) < 8 or len(fact) > MAX_MEMORY_CHARS:
                continue
            norm = _strip_for_embedding(fact)
            ch = _hashlib.sha256(norm.encode("utf-8")).hexdigest()
            exists = self._db.execute(
                "SELECT 1 FROM vectors WHERE kind='ltm' AND content_hash=? LIMIT 1",
                (ch,),
            ).fetchone()
            if exists:
                continue
            mid = uuid.uuid4().hex
            self._db.execute(
                "INSERT INTO vectors (id, kind, channel_id, guild_id, author, "
                "author_id, source, content, content_hash, embedding, metadata, "
                "scope, importance, parent_id, chunk_index, downvotes, timestamp, "
                "created_at) "
                "VALUES (?, 'ltm', '', '', 'system', 'system', 'user', ?, ?, "
                "NULL, '{\"source\":\"auto_summary\"}', 'global', 5, '', 0, 0, "
                "?, ?)",
                (mid, fact[:MAX_MEMORY_CHARS], ch, _utcnow_iso(), time.time()),
            )
            self._spawn(self._embed_and_store(mid, fact))
            added += 1
        if added:
            logger.info(f"LTM summarizer added {added} facts")
        return added

    async def _call_ltm_extractor(
        self, transcript: str, max_facts: int = 20
    ) -> list[str]:
        """Subclass-overridable hook. Default: ask no-one (no LLM wired).

        Returns a list of fact strings. Bot.py should override this method
        on the manager instance after creating it, OR pass a real
        ``_ltm_summarizer_fn`` callback when wiring up. Keeping it as a
        stub here means the import-and-run path doesn't blow up if the
        bot hasn't installed the LLM bridge yet.
        """
        fn = getattr(self, "_ltm_summarizer_fn", None)
        if not fn:
            return []
        try:
            result = await fn(transcript, max_facts=max_facts)
            if isinstance(result, list):
                return [str(x) for x in result if x]
        except Exception as e:
            logger.warning(f"_call_ltm_extractor failed: {e}")
        return []

    # ─── RAG search (new) ─────────────────────────────────────────

    async def rag_search(
        self,
        query: str,
        kinds: list[str] | None = None,
        channel_id: str = "",
        guild_id: str = "",
        source: str | list[str] | None = None,
        top_k: int = 10,
        min_similarity: float = SIM_THRESHOLD,
        apply_recency: bool = True,
        recency_tau_days: float | None = None,  # override global RECENCY_TAU_SECONDS
        exclude_negatives: bool = True,
        over_fetch: int = 3,
    ) -> list[dict]:
        """Semantic search across the vector store.

        Args:
            query: search text
            kinds: filter by kind ('message', 'ltm', 'shared_context',
                   'bot_output', 'negative')
            channel_id: filter messages by channel; matches exact channel
                        OR global (channel_id='') by default
            guild_id: NEW — if set, restrict to this server (discord)
            source: NEW — 'user' | 'bot' | 'system' filter; or list of those
            top_k: max results to RETURN (after scoring)
            min_similarity: cosine similarity cutoff
            apply_recency: NEW — multiply score by recency decay
            recency_tau_days: NEW — override the default 14-day recency τ.
                        Pass 3.0 for "give me recent chat", 0.5 for
                        "today's conversation only", 30.0 for "month
                        of context". None = use module default.
            exclude_negatives: NEW — exclude rows similar to anything in
                                kind='negative'
            over_fetch: NEW — internally pull top_k*over_fetch candidates
                        from cosine before applying recency/rerank/dedup
                        (gives room for filtering without starving the limit)

        Returns list of dicts with: id, kind, content, author, channel_id,
            guild_id, timestamp, similarity, score (recency-decayed),
            metadata.
        """
        query_vec = await self._embed(query)
        if query_vec is None:
            return []

        # Per-call override of recency tau. Caller passes recency_tau_days;
        # we expose `_score_with_recency_tau` so the multiplier uses the
        # caller's value rather than the module-level constant.
        if recency_tau_days is not None:
            _tau_seconds = float(recency_tau_days) * 86400.0
            # Re-bind locally so the score function uses this tau
            import math

            def _decay(ts_str):
                if not ts_str:
                    return 1.0
                dt = _parse_iso(ts_str)
                if dt is None:
                    return 1.0
                age = max(0.0, _utcnow().timestamp() - dt.timestamp())
                decay = math.exp(-age / max(1.0, _tau_seconds))
                return 0.25 + 0.75 * decay
        else:

            def _decay(ts_str):
                return _score_with_recency(1.0, ts_str)  # just the multiplier

        # ─── build SQL ───────────────────────────────────────────────
        where_parts = ["embedding IS NOT NULL"]
        params: list = []
        if kinds:
            placeholders = ",".join("?" * len(kinds))
            where_parts.append(f"kind IN ({placeholders})")
            params.extend(kinds)
        if channel_id:
            where_parts.append("(channel_id=? OR channel_id='')")
            params.append(str(channel_id))
        if guild_id:
            where_parts.append("(guild_id=? OR guild_id='')")
            params.append(str(guild_id))
        if source:
            src = [source] if isinstance(source, str) else list(source)
            placeholders = ",".join("?" * len(src))
            where_parts.append(f"source IN ({placeholders})")
            params.extend(src)

        where_clause = " AND ".join(where_parts)
        rows = self._db.execute(
            f"SELECT id, kind, channel_id, guild_id, author, author_id, source, "
            f"content, embedding, metadata, scope, importance, parent_id, "
            f"downvotes, timestamp FROM vectors WHERE {where_clause}",
            params,
        ).fetchall()

        if not rows:
            return []

        # ─── score ───────────────────────────────────────────────────
        results = []
        query_norm = query_vec / (np.linalg.norm(query_vec) + 1e-8)
        for row in rows:
            blob = row["embedding"]
            if not blob:
                continue
            try:
                vec = _blob_to_embedding(blob)
                if len(vec) != EMBED_DIM:
                    continue
                vec_norm = vec / (np.linalg.norm(vec) + 1e-8)
                sim = float(np.dot(query_norm, vec_norm))
                if sim < min_similarity:
                    continue
                # Downvoted rows are pulled in scoring but pulled down.
                if row["downvotes"]:
                    sim *= max(0.05, 1.0 - 0.2 * row["downvotes"])
                if apply_recency and row["kind"] in ("message", "bot_output"):
                    if recency_tau_days is not None:
                        # _decay(ts) returns the multiplier (0.25..1.0).
                        score = sim * _decay(row["timestamp"])
                    else:
                        score = _score_with_recency(sim, row["timestamp"])
                else:
                    score = sim
                entry = {
                    "id": row["id"],
                    "kind": row["kind"],
                    "channel_id": row["channel_id"],
                    "guild_id": row["guild_id"],
                    "author": row["author"],
                    "author_id": row["author_id"],
                    "source": row["source"],
                    "content": row["content"],
                    "scope": row["scope"],
                    "importance": row["importance"],
                    "timestamp": row["timestamp"],
                    "similarity": sim,
                    "score": score,
                    "downvotes": row["downvotes"],
                }
                try:
                    meta = json.loads(row["metadata"] or "{}")
                    entry.update(meta)
                except Exception:
                    pass
                results.append(entry)
            except Exception:
                continue

        # Sort by decayed score (not raw cosine) so recent-but-slightly-less-
        # similar memories beat older more-similar ones.
        results.sort(key=lambda x: x["score"], reverse=True)

        # Over-fetch up to top_k * over_fetch so we have candidates to
        # filter through the next step.
        candidates = results[: top_k * over_fetch]

        # ─── exclude negatives ───────────────────────────────────────
        # Compare each candidate's embedding against everything in
        # kind='negative'. If cosine ≥ 0.85, drop the candidate.
        # Negatives are rare so this is cheap.
        if exclude_negatives:
            try:
                neg_rows = self._db.execute(
                    "SELECT embedding FROM vectors WHERE kind='negative' "
                    "AND embedding IS NOT NULL"
                ).fetchall()
                if neg_rows:
                    neg_vecs = []
                    for nr in neg_rows:
                        nb = nr["embedding"]
                        if not nb:
                            continue
                        nv = _blob_to_embedding(nb)
                        if len(nv) == EMBED_DIM:
                            nv_norm = nv / (np.linalg.norm(nv) + 1e-8)
                            neg_vecs.append(nv_norm)
                    if neg_vecs:
                        neg_stack = np.stack(neg_vecs)
                        filtered = []
                        for c in candidates:
                            blob = None
                            for r in rows:
                                if r["id"] == c["id"]:
                                    blob = r["embedding"]
                                    break
                            if not blob:
                                filtered.append(c)
                                continue
                            cv = _blob_to_embedding(blob)
                            cv_norm = cv / (np.linalg.norm(cv) + 1e-8)
                            # max cosine with any negative
                            max_neg_sim = float(np.max(neg_stack @ cv_norm))
                            if max_neg_sim >= 0.85:
                                continue  # too similar to a known bad rec
                            filtered.append(c)
                        candidates = filtered
            except Exception as e:
                logger.debug(f"negative exclusion skipped: {e}")

        # ─── done ────────────────────────────────────────────────────
        candidates.sort(key=lambda x: x.get("score", 0.0), reverse=True)
        return candidates[:top_k]  # type: ignore[index]  # always len > 0 here

    async def rag_relevant_context(  # type: ignore[override]
        self,
        query: str,
        channel_id: str = "",
        guild_id: str = "",
        top_k: int = 15,
    ) -> list[dict]:
        """Get semantically relevant context for a user message.

        Searches across user messages, LTM, shared context. Excludes bot
        outputs and system events from the primary mix unless everything
        comes back thin. Diversifies by kind.
        """
        results = await self.rag_search(
            query,
            kinds=["message", "ltm", "shared_context"],
            channel_id=channel_id,
            guild_id=guild_id,
            source=["user"],  # user messages dominate the mix
            top_k=top_k * 3,
            apply_recency=True,
            exclude_negatives=True,
        )
        if len(results) < top_k:
            # Fall back: include bot context if user context is thin
            results.extend(
                await self.rag_search(
                    query,
                    kinds=["bot_output", "ltm", "shared_context"],
                    channel_id=channel_id,
                    guild_id=guild_id,
                    top_k=top_k * 2,
                    apply_recency=True,
                    exclude_negatives=True,
                )
            )

        # Deduplicate by content similarity
        seen: set[str] = set()
        deduped: list[dict] = []
        for r in results:
            key = str(r["content"])[:200].lower()
            if key in seen:
                continue
            seen.add(key)
            deduped.append(r)

        # Diversify by kind. Mix LTM/shared_context at top, then recent
        # user messages. Bot outputs last.
        by_kind: dict[str, list[dict]] = {
            "ltm": [],
            "shared_context": [],
            "message": [],
            "bot_output": [],
        }
        for r in deduped:
            by_kind.setdefault(r["kind"], []).append(r)

        mixed: list[dict] = []
        for kind in ("ltm", "shared_context", "message", "bot_output"):
            take = max(1, top_k // 3) if kind in ("ltm", "shared_context") else top_k
            mixed.extend(by_kind.get(kind, [])[:take])

        # Promote the top-1 LTM / shared_context to the very front for
        # durable-fact primacy in the prompt.
        for i, r in enumerate(mixed):
            if r["kind"] in ("ltm", "shared_context"):
                mixed.insert(0, mixed.pop(i))
                break

        return mixed[:top_k]  # type: ignore[index]  # always len > 0

    # ─── lifecycle ────────────────────────────────────────────────

    async def flush(self):
        """Await in-flight embed tasks so shutdown doesn't drop rows.

        SQLite writes are autocommit; the only pending state is background
        embedding. Previously these were fire-and-forget tasks: on PM2
        restart / bot shutdown the loop closed mid-embed, rows stayed with
        embedding=NULL, and tests spammed "coroutine ignored GeneratorExit"
        and "Event loop is closed" warnings.
        """
        if self._embed_tasks:
            pending = list(self._embed_tasks)
            try:
                await asyncio.gather(*pending, return_exceptions=True)
            except Exception as e:
                logger.warning(f"Error awaiting embed tasks during flush: {e}")
        self._embed_tasks.clear()

    def load_from_disk(self):
        """No-op — DB is loaded in __init__. Kept for interface compat."""
        pass
