"""RAG vector memory for Maxwell Bot.

Replaces the old MemoryManager (memory.py) and ContextCleanupEngine
(context_cleanup.py) with a single SQLite + numpy vector store backed by
qwen3-embedding:0.6b via ollama.

Architecture:
  - SQLite database at data/maxwell_rag.db
  - Three logical stores in one table: channel messages, long-term facts,
    shared context entries — distinguished by `kind`
  - Each row stores the text, metadata JSON, and a 1024-dim embedding BLOB
  - Retrieval: cosine similarity via numpy dot product against the query
    embedding, filtered by kind/channel/scope as needed
  - Embeddings generated by POSTing to ollama's /api/embed endpoint

The public interface mirrors the old MemoryManager so bot.py changes are
minimal — same method names, same return shapes.
"""

import asyncio
import json
import logging
import sqlite3
import struct
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path

import aiohttp
import numpy as np

logger = logging.getLogger(__name__)

# ─── constants ────────────────────────────────────────────────────────

EMBED_MODEL = "qwen3-embedding:0.6b"
EMBED_DIM = 1024  # qwen3-embedding:0.6b output dimension
OLLAMA_EMBED_URL = "http://localhost:11434/api/embed"
MAX_CHANNELS = 25
MAX_MEMORY_CHARS = 1000
MAX_LTM_LINES = 999
DEFAULT_REM_EVENT_BUFFER_MAX = 500

# Cosine similarity threshold for RAG retrieval. Below this, results are
# considered noise and filtered out.
SIM_THRESHOLD = 0.35

# ─── helpers ──────────────────────────────────────────────────────────


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _utcnow_iso() -> str:
    return _utcnow().isoformat()


def _parse_iso(ts: str) -> datetime | None:
    if not ts:
        return None
    try:
        dt = datetime.fromisoformat(str(ts))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    except Exception:
        return None


def _normalize_ltm_line(content: str) -> str:
    return " ".join(str(content).split())[:MAX_MEMORY_CHARS]


def _strip_reasoning_text(content: str) -> str:
    import re

    text = str(content or "")
    text = re.sub(
        r"<think\b[^>]*>.*?</think>", "", text, flags=re.IGNORECASE | re.DOTALL
    )
    return " ".join(text.split())


def _embedding_to_blob(vec: np.ndarray) -> bytes:
    """Store float32 embedding as compact BLOB."""
    return vec.astype(np.float32).tobytes()


def _blob_to_embedding(blob: bytes) -> np.ndarray:
    """Unpack BLOB back to float32 numpy array."""
    return np.frombuffer(blob, dtype=np.float32)


# ─── RemEventLog (kept identical — REM still uses it) ────────────────


class RemEventLog:
    """JSON-backed visible event ring for REM assimilation."""

    def __init__(self, data_dir: str, max_events: int = DEFAULT_REM_EVENT_BUFFER_MAX):
        self.data_dir = Path(data_dir)
        self.events_file = self.data_dir / "rem_events.json"
        self.max_events = max(1, int(max_events or DEFAULT_REM_EVENT_BUFFER_MAX))
        self.events = []
        self._lock = asyncio.Lock()
        self._dirty = False
        self._save_task = None
        self._pending_save = None
        self._save_lock = asyncio.Lock()

    def load_from_disk(self):
        try:
            if self.events_file.exists():
                data = json.loads(self.events_file.read_text(encoding="utf-8"))
                self.events = self._sanitize_events(
                    data if isinstance(data, list) else []
                )
        except (json.JSONDecodeError, OSError) as e:
            logger.error(f"Failed to load REM events: {e}")
            self.events = []

    def _sanitize_events(self, events: list) -> list:
        clean = []
        for raw in events:
            if not isinstance(raw, dict):
                continue
            role = str(raw.get("role") or "")
            if role not in {"user", "assistant"}:
                # Also accept events with kind/timestamp format (used by bot.py)
                if not raw.get("kind") and not raw.get("timestamp"):
                    continue
                # Convert kind-based events to the expected format
                role = str(raw.get("kind") or "user")
            mentions = []
            for row in list(raw.get("mentions") or [])[:10]:
                if not isinstance(row, dict):
                    continue
                mid = str(row.get("id") or "")
                if not mid:
                    continue
                mentions.append({"id": mid, "name": str(row.get("name") or mid)[:120]})
            clean.append(
                {
                    "ts": str(raw.get("ts") or raw.get("timestamp") or _utcnow_iso()),
                    "channel_id": str(raw.get("channel_id") or ""),
                    "guild_id": str(raw.get("guild_id"))
                    if raw.get("guild_id") is not None
                    else None,
                    "message_id": str(raw.get("message_id") or ""),
                    "user_id": str(raw.get("user_id") or ""),
                    "user_name": str(raw.get("user_name") or "")[:120],
                    "role": role,
                    "content": _strip_reasoning_text(raw.get("content", ""))[:4000],
                    "mentions": mentions,
                    "reply_to_message_id": str(raw.get("reply_to_message_id") or ""),
                    "reply_to_author": str(raw.get("reply_to_author") or "")[:120],
                    "reply_to_author_id": str(raw.get("reply_to_author_id") or ""),
                    "reply_to_self": bool(raw.get("reply_to_self", False)),
                    "auto_mode": bool(raw.get("auto_mode", False)),
                    "id": str(raw.get("id") or ""),
                    "kind": str(raw.get("kind") or role),
                    "timestamp": str(raw.get("timestamp") or _utcnow_iso()),
                }
            )
        return clean[-self.max_events :]

    async def _atomic_save(self, snapshot: list):
        async with self._save_lock:
            from utils import _atomic_json_write_sync

            await asyncio.to_thread(_atomic_json_write_sync, self.events_file, snapshot)

    def _schedule_save(self):
        self._dirty = True
        if self._save_task is not None:
            self._save_task.cancel()
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            return

        async def _debounced():
            try:
                await asyncio.sleep(5)
                await self._do_save()
            except asyncio.CancelledError:
                pass

        self._save_task = loop.create_task(_debounced())

    async def _do_save(self):
        self._save_task = None
        if self._dirty:
            self._dirty = False
            snapshot = list(self.events)
            await self._atomic_save(snapshot)

    async def record(self, event: dict):
        async with self._lock:
            # Sanitize through _sanitize_events to get consistent format
            clean = self._sanitize_events([event])
            if not clean or not clean[0]["content"]:
                return
            self.events.append(clean[0])
            if len(self.events) > self.max_events:
                self.events = self.events[-self.max_events :]
            self._schedule_save()

    async def drain_slice(self, since_ts: str | None = None) -> list:
        since = _parse_iso(since_ts or "")
        async with self._lock:
            if since is None:
                return [dict(e) for e in self.events]
            out = []
            for event in self.events:
                ts = _parse_iso(event.get("ts", event.get("timestamp", "")))
                if ts and ts > since:
                    out.append(dict(event))
            return out

    async def size(self) -> int:
        async with self._lock:
            return len(self.events)

    async def flush(self):
        async with self._lock:
            if self._save_task:
                self._save_task.cancel()
                self._save_task = None
            self._dirty = True
            await self._do_save()


# ─── RAGMemoryManager ────────────────────────────────────────────────


class RAGMemoryManager:
    """Vector-backed memory manager. Drop-in replacement for MemoryManager.

    Stores channel messages, long-term facts, and shared context entries
    in a single SQLite table with embeddings. Retrieval uses cosine
    similarity for semantic search (RAG).

    Public interface matches the old MemoryManager:
      - get_channel_memory(channel_id) -> list[dict]
      - add_to_channel_memory(channel_id, message) -> None
      - clear_channel_memory(channel_id) -> None
      - get_long_term_memory() -> list[dict]
      - add_long_term_memory(content) -> str
      - edit_long_term_memory(memory_id, content) -> bool
      - remove_long_term_memory(memory_id) -> bool
      - apply_ltm_batch(ops) -> dict
      - get_server_prompt(server_id) -> str | None
      - set_server_prompt(server_id, prompt) -> None
      - clear_server_prompt(server_id) -> None
      - add_shared_context(entry) -> str
      - remove_shared_context(context_id) -> bool
      - update_shared_context(context_id, updates) -> bool
      - list_shared_context(limit) -> list
      - get_relevant_shared_context(...) -> list

    New RAG-specific methods:
      - rag_search(query, kinds, channel_id, top_k) -> list[dict]
      - rag_relevant_context(query, channel_id, top_k) -> list[dict]
    """

    def __init__(self, data_dir: str, max_messages: int = 10000):
        self.data_dir = Path(data_dir)
        self.max_messages = min(max_messages, 10000)
        self.db_path = self.data_dir / "maxwell_rag.db"
        self.prompts_file = self.data_dir / "prompts.json"
        self._db: sqlite3.Connection | None = None
        self._lock = asyncio.Lock()
        self._embed_semaphore = asyncio.Semaphore(4)  # limit concurrent embed calls
        self._embed_cache: dict[str, np.ndarray] = {}  # text hash -> embedding
        self._prompts: dict[str, str] = {}
        self._init_db()

    def _init_db(self):
        """Create SQLite DB and tables."""
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self._db = sqlite3.connect(
            str(self.db_path),
            check_same_thread=False,
            isolation_level=None,  # autocommit
        )
        self._db.row_factory = sqlite3.Row
        self._db.execute("PRAGMA journal_mode=WAL")
        self._db.execute("PRAGMA synchronous=NORMAL")
        self._db.execute("PRAGMA cache_size=-64000")  # 64MB cache

        self._db.execute(
            """
            CREATE TABLE IF NOT EXISTS vectors (
                id TEXT PRIMARY KEY,
                kind TEXT NOT NULL,           -- 'message', 'ltm', 'shared_context'
                channel_id TEXT DEFAULT '',
                author TEXT DEFAULT '',
                author_id TEXT DEFAULT '',
                content TEXT NOT NULL,
                embedding BLOB,
                metadata TEXT DEFAULT '{}',
                scope TEXT DEFAULT '',
                importance INTEGER DEFAULT 0,
                timestamp TEXT NOT NULL,
                created_at REAL NOT NULL
            )
            """
        )
        self._db.execute(
            "CREATE INDEX IF NOT EXISTS idx_kind ON vectors(kind)"
        )
        self._db.execute(
            "CREATE INDEX IF NOT EXISTS idx_channel ON vectors(channel_id)"
        )
        self._db.execute(
            "CREATE INDEX IF NOT EXISTS idx_kind_channel ON vectors(kind, channel_id)"
        )
        self._db.execute(
            "CREATE INDEX IF NOT EXISTS idx_timestamp ON vectors(timestamp)"
        )

        # Migrate prompts
        try:
            if self.prompts_file.exists():
                data = json.loads(self.prompts_file.read_text(encoding="utf-8"))
                if isinstance(data, dict):
                    self._prompts = {str(k): str(v) for k, v in data.items()}
        except Exception as e:
            logger.warning(f"Failed to load prompts: {e}")
            self._prompts = {}

        # Migrate existing long_term_memory.txt if present
        self._migrate_ltm()
        # Migrate existing shared_context.json if present
        self._migrate_shared_context()

        logger.info(
            f"RAGMemoryManager initialized at {self.db_path} "
            f"({self._count_all()} vectors)"
        )

    def _count_all(self) -> int:
        try:
            row = self._db.execute("SELECT COUNT(*) as c FROM vectors").fetchone()
            return row["c"] if row else 0
        except Exception:
            return 0

    def _migrate_ltm(self):
        """One-time migration of long_term_memory.txt into the vector DB."""
        ltm_file = self.data_dir / "long_term_memory.txt"
        if not ltm_file.exists():
            return
        # Check if we already migrated (any LTM rows exist)
        try:
            row = self._db.execute(
                "SELECT COUNT(*) as c FROM vectors WHERE kind='ltm'"
            ).fetchone()
            if row and row["c"] > 0:
                return  # already migrated
        except Exception:
            pass

        try:
            lines = ltm_file.read_text(encoding="utf-8").strip().splitlines()
            migrated = 0
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                # Try to parse old format: "content|timestamp|id" or just "content"
                parts = line.split("|")
                content = parts[0].strip() if parts else line
                ts = parts[1].strip() if len(parts) > 1 else _utcnow_iso()
                mid = parts[2].strip() if len(parts) > 2 else uuid.uuid4().hex

                # Insert without embedding first (will be embedded lazily on search)
                self._db.execute(
                    "INSERT OR IGNORE INTO vectors (id, kind, channel_id, author, author_id, content, embedding, metadata, scope, importance, timestamp, created_at) VALUES (?, 'ltm', '', '', '', ?, NULL, '{}', 'global', 5, ?, ?)",
                    (content[:MAX_MEMORY_CHARS], ts, time.time()),
                )
                migrated += 1
            if migrated:
                logger.info(f"Migrated {migrated} LTM lines from long_term_memory.txt")
                # Embed them in background
                asyncio.ensure_future(self._embed_pending("ltm"))
        except Exception as e:
            logger.warning(f"LTM migration failed: {e}")

    def _migrate_shared_context(self):
        """One-time migration of shared_context.json into the vector DB."""
        sc_file = self.data_dir / "shared_context.json"
        if not sc_file.exists():
            return
        try:
            row = self._db.execute(
                "SELECT COUNT(*) as c FROM vectors WHERE kind='shared_context'"
            ).fetchone()
            if row and row["c"] > 0:
                return  # already migrated
        except Exception:
            pass

        try:
            data = json.loads(sc_file.read_text(encoding="utf-8"))
            if not isinstance(data, list):
                return
            migrated = 0
            for entry in data:
                if not isinstance(entry, dict):
                    continue
                cid = str(entry.get("id") or uuid.uuid4().hex)
                content = str(entry.get("content") or "")[:1200]
                scope = str(entry.get("scope") or "global")
                importance = int(entry.get("importance") or 5)
                ts = str(entry.get("timestamp") or _utcnow_iso())
                metadata = json.dumps(
                    {k: v for k, v in entry.items() if k not in ("id", "content", "scope", "importance", "timestamp")}
                )
                self._db.execute(
                    "INSERT OR IGNORE INTO vectors (id, kind, channel_id, author, author_id, content, embedding, metadata, scope, importance, timestamp, created_at) VALUES (?, 'shared_context', '', '', '', ?, NULL, ?, ?, ?, ?, ?)",
                    (cid, content, metadata, scope, importance, ts, time.time()),
                )
                migrated += 1
            if migrated:
                logger.info(f"Migrated {migrated} shared context entries")
                asyncio.ensure_future(self._embed_pending("shared_context"))
        except Exception as e:
            logger.warning(f"Shared context migration failed: {e}")

    # ─── embedding ──────────────────────────────────────────────────

    async def _embed(self, text: str) -> np.ndarray | None:
        """Generate embedding via ollama. Returns float32 numpy array or None."""
        text = str(text or "").strip()
        if not text:
            return None

        # Cache check (use hash of text for cache key)
        import hashlib

        cache_key = hashlib.md5(text.encode()).hexdigest()
        if cache_key in self._embed_cache:
            return self._embed_cache[cache_key]

        # Truncate very long text before embedding
        if len(text) > 8000:
            text = text[:8000]

        payload = {"model": EMBED_MODEL, "input": text}

        try:
            async with self._embed_semaphore:
                async with aiohttp.ClientSession() as session:
                    async with session.post(
                        OLLAMA_EMBED_URL,
                        json=payload,
                        timeout=aiohttp.ClientTimeout(total=30),
                    ) as resp:
                        if resp.status != 200:
                            body = await resp.text()
                            logger.warning(
                                f"Embedding API returned {resp.status}: {body[:200]}"
                            )
                            return None
                        data = await resp.json()
                        embeddings = data.get("embeddings") or []
                        if not embeddings:
                            # Try single 'embedding' field (older API)
                            emb = data.get("embedding")
                            if emb:
                                embeddings = [emb]
                        if not embeddings:
                            logger.warning("Embedding API returned no embeddings")
                            return None
                        vec = np.array(embeddings[0], dtype=np.float32)
                        if len(vec) != EMBED_DIM:
                            logger.warning(
                                f"Embedding dimension mismatch: {len(vec)} != {EMBED_DIM}"
                            )
                            return None
                        self._embed_cache[cache_key] = vec
                        return vec
        except asyncio.TimeoutError:
            logger.warning("Embedding API timeout")
            return None
        except Exception as e:
            logger.warning(f"Embedding failed: {e}")
            return None

    async def _embed_and_store(self, row_id: str, text: str):
        """Generate embedding and update the row in DB."""
        vec = await self._embed(text)
        if vec is not None:
            blob = _embedding_to_blob(vec)
            self._db.execute(
                "UPDATE vectors SET embedding=? WHERE id=?",
                (blob, row_id),
            )

    async def _embed_pending(self, kind: str):
        """Embed all rows of a kind that don't have embeddings yet."""
        try:
            rows = self._db.execute(
                "SELECT id, content FROM vectors WHERE kind=? AND embedding IS NULL",
                (kind,),
            ).fetchall()
            for row in rows:
                await self._embed_and_store(row["id"], row["content"])
            if rows:
                logger.info(f"Embedded {len(rows)} pending {kind} vectors")
        except Exception as e:
            logger.warning(f"Failed to embed pending {kind}: {e}")

    async def _embed_pending_all(self, batch_size: int = 50):
        """Embed ALL rows without embeddings, in batches. Used for migration.
        
        Uses ollama's batch embed API to speed up — sends multiple texts
        in a single request instead of one-at-a-time.
        """
        try:
            total_embedded = 0
            while True:
                rows = self._db.execute(
                    "SELECT id, content FROM vectors WHERE embedding IS NULL LIMIT ?",
                    (batch_size,),
                ).fetchall()
                if not rows:
                    break

                # Batch embed: send all texts in one request
                texts = [row["content"][:8000] for row in rows]
                payload = {"model": EMBED_MODEL, "input": texts}

                try:
                    async with self._embed_semaphore:
                        async with aiohttp.ClientSession() as session:
                            async with session.post(
                                OLLAMA_EMBED_URL,
                                json=payload,
                                timeout=aiohttp.ClientTimeout(total=120),
                            ) as resp:
                                if resp.status != 200:
                                    body = await resp.text()
                                    logger.warning(
                                        f"Batch embed API returned {resp.status}: {body[:200]}"
                                    )
                                    # Fall back to one-by-one
                                    for row in rows:
                                        await self._embed_and_store(row["id"], row["content"])
                                        total_embedded += 1
                                    continue
                                data = await resp.json()
                                embeddings = data.get("embeddings") or []
                                if not embeddings:
                                    logger.warning("Batch embed returned no embeddings")
                                    continue
                                for i, row in enumerate(rows):
                                    if i < len(embeddings):
                                        vec = np.array(embeddings[i], dtype=np.float32)
                                        if len(vec) == EMBED_DIM:
                                            blob = _embedding_to_blob(vec)
                                            self._db.execute(
                                                "UPDATE vectors SET embedding=? WHERE id=?",
                                                (blob, row["id"]),
                                            )
                                            total_embedded += 1
                except Exception as e:
                    logger.warning(f"Batch embed failed: {e}")
                    # Fall back to one-by-one for this batch
                    for row in rows:
                        await self._embed_and_store(row["id"], row["content"])
                        total_embedded += 1

            if total_embedded:
                logger.info(f"Batch-embedded {total_embedded} vectors total")
        except Exception as e:
            logger.warning(f"Failed to embed pending vectors: {e}")

    # ─── channel memory (short-term) ──────────────────────────────

    async def get_channel_memory(self, channel_id: str) -> list[dict]:
        """Return recent messages for a channel, oldest first."""
        rows = self._db.execute(
            "SELECT id, author, author_id, content, timestamp, metadata FROM vectors WHERE kind='message' AND channel_id=? ORDER BY created_at DESC LIMIT ?",
            (str(channel_id), self.max_messages),
        ).fetchall()
        # Reverse to oldest-first, and build dict entries matching old format
        result = []
        for row in reversed(rows):
            entry = {
                "author": row["author"],
                "author_id": row["author_id"],
                "content": row["content"],
                "message_id": row["id"],
                "timestamp": row["timestamp"],
            }
            try:
                meta = json.loads(row["metadata"] or "{}")
                entry.update(meta)
            except Exception:
                pass
            result.append(entry)
        return result

    async def add_to_channel_memory(self, channel_id: str, message: dict):
        """Add a message to channel memory with embedding."""
        channel_id = str(channel_id)
        msg_id = str(message.get("message_id") or uuid.uuid4().hex)
        content = str(message.get("content") or "")
        author = str(message.get("author") or "")
        author_id = str(message.get("author_id") or "")
        ts = str(message.get("timestamp") or _utcnow_iso())

        # Build metadata from extra fields
        meta_keys = {
            "author_is_bot",
            "mentions",
            "reply_to_message_id",
            "reply_to_author",
            "reply_to_author_id",
            "reply_to_self",
            "is_tool",
            "tool_name",
            "tool_params",
            "tool_result",
            "tool_error",
            "tool_cost",
        }
        metadata = {k: v for k, v in message.items() if k in meta_keys and v is not None}

        # Delete existing message with same id (dedup)
        self._db.execute("DELETE FROM vectors WHERE id=?", (msg_id,))

        # Insert
        self._db.execute(
            "INSERT INTO vectors (id, kind, channel_id, author, author_id, content, embedding, metadata, scope, importance, timestamp, created_at) VALUES (?, 'message', ?, ?, ?, ?, NULL, ?, '', 0, ?, ?)",
            (
                msg_id,
                channel_id,
                author,
                author_id,
                content[:8000],
                json.dumps(metadata),
                ts,
                time.time(),
            ),
        )

        # Prune old messages for this channel
        count_row = self._db.execute(
            "SELECT COUNT(*) as c FROM vectors WHERE kind='message' AND channel_id=?",
            (channel_id,),
        ).fetchone()
        if count_row and count_row["c"] > self.max_messages:
            excess = count_row["c"] - self.max_messages
            self._db.execute(
                "DELETE FROM vectors WHERE id IN (SELECT id FROM vectors WHERE kind='message' AND channel_id=? ORDER BY created_at ASC LIMIT ?)",
                (channel_id, excess),
            )

        # Prune channels if too many
        chan_rows = self._db.execute(
            "SELECT channel_id, COUNT(*) as c FROM vectors WHERE kind='message' GROUP BY channel_id ORDER BY MAX(created_at) DESC"
        ).fetchall()
        if len(chan_rows) > MAX_CHANNELS:
            for row in chan_rows[MAX_CHANNELS:]:
                self._db.execute(
                    "DELETE FROM vectors WHERE kind='message' AND channel_id=?",
                    (row["channel_id"],),
                )

        # Embed in background (non-blocking)
        asyncio.ensure_future(self._embed_and_store(msg_id, content))

    async def clear_channel_memory(self, channel_id: str):
        self._db.execute(
            "DELETE FROM vectors WHERE kind='message' AND channel_id=?",
            (str(channel_id),),
        )

    # ─── long-term memory ─────────────────────────────────────────

    def get_long_term_memory(self) -> list[dict]:
        """Return all LTM entries (sync, for backwards compat)."""
        rows = self._db.execute(
            "SELECT id, content, timestamp FROM vectors WHERE kind='ltm' ORDER BY created_at ASC"
        ).fetchall()
        return [
            {
                "id": row["id"],
                "content": row["content"],
                "timestamp": row["timestamp"],
            }
            for row in rows
        ]

    async def add_long_term_memory(self, content: str) -> str:
        content = _normalize_ltm_line(content)
        mid = uuid.uuid4().hex
        ts = _utcnow_iso()
        self._db.execute(
            "INSERT INTO vectors (id, kind, channel_id, author, author_id, content, embedding, metadata, scope, importance, timestamp, created_at) VALUES (?, 'ltm', '', '', '', ?, NULL, '{}', 'global', 5, ?, ?)",
            (mid, content, ts, time.time()),
        )
        # Prune if exceeding max
        count_row = self._db.execute(
            "SELECT COUNT(*) as c FROM vectors WHERE kind='ltm'"
        ).fetchone()
        if count_row and count_row["c"] > MAX_LTM_LINES:
            excess = count_row["c"] - MAX_LTM_LINES
            self._db.execute(
                "DELETE FROM vectors WHERE id IN (SELECT id FROM vectors WHERE kind='ltm' ORDER BY created_at ASC LIMIT ?)",
                (excess,),
            )
        # Embed in background
        asyncio.ensure_future(self._embed_and_store(mid, content))
        return mid

    async def edit_long_term_memory(self, memory_id: str, content: str) -> bool:
        content = _normalize_ltm_line(content)
        cursor = self._db.execute(
            "UPDATE vectors SET content=?, embedding=NULL WHERE id=? AND kind='ltm'",
            (content, str(memory_id)),
        )
        if cursor.rowcount > 0:
            asyncio.ensure_future(self._embed_and_store(str(memory_id), content))
            return True
        return False

    async def remove_long_term_memory(self, memory_id: str) -> bool:
        cursor = self._db.execute(
            "DELETE FROM vectors WHERE id=? AND kind='ltm'", (str(memory_id),)
        )
        return cursor.rowcount > 0

    async def apply_ltm_batch(self, ops: list[dict]) -> dict:
        """Apply batch LTM operations (add/edit/delete)."""
        added = 0
        edited = 0
        deleted = 0
        errors = 0
        for op in ops:
            try:
                kind = str(op.get("kind") or op.get("op") or "")
                if kind == "add":
                    content = str(op.get("content") or "")
                    if content:
                        await self.add_long_term_memory(content)
                        added += 1
                elif kind == "edit":
                    mid = str(op.get("id") or "")
                    content = str(op.get("content") or "")
                    if mid and content:
                        if await self.edit_long_term_memory(mid, content):
                            edited += 1
                        else:
                            errors += 1
                elif kind == "delete":
                    mid = str(op.get("id") or "")
                    if mid:
                        if await self.remove_long_term_memory(mid):
                            deleted += 1
                        else:
                            errors += 1
            except Exception as e:
                logger.warning(f"LTM batch op failed: {e}")
                errors += 1
        return {"added": added, "edited": edited, "deleted": deleted, "errors": errors}

    # ─── server prompts (kept as JSON file) ───────────────────────

    def get_server_prompt(self, server_id: str) -> str | None:
        return self._prompts.get(str(server_id))

    def set_server_prompt(self, server_id: str, prompt: str):
        self._prompts[str(server_id)] = str(prompt)
        self._save_prompts()

    def clear_server_prompt(self, server_id: str):
        self._prompts.pop(str(server_id), None)
        self._save_prompts()

    def _save_prompts(self):
        try:
            from utils import _atomic_json_write_sync

            _atomic_json_write_sync(self.prompts_file, self._prompts)
        except Exception as e:
            logger.error(f"Failed to save prompts: {e}")

    # ─── shared context ───────────────────────────────────────────

    async def add_shared_context(self, entry: dict) -> str:
        cid = str(entry.get("id") or uuid.uuid4().hex)
        content = str(entry.get("content") or "")[:1200]
        scope = str(entry.get("scope") or "global")
        importance = int(entry.get("importance") or 5)
        ts = str(entry.get("timestamp") or _utcnow_iso())
        metadata = json.dumps(
            {k: v for k, v in entry.items() if k not in ("id", "content", "scope", "importance", "timestamp")}
        )
        self._db.execute(
            "INSERT OR REPLACE INTO vectors (id, kind, channel_id, author, author_id, content, embedding, metadata, scope, importance, timestamp, created_at) VALUES (?, 'shared_context', '', '', '', ?, NULL, ?, ?, ?, ?, ?)",
            (cid, content, metadata, scope, importance, ts, time.time()),
        )
        asyncio.ensure_future(self._embed_and_store(cid, content))
        return cid

    async def remove_shared_context(self, context_id: str) -> bool:
        cursor = self._db.execute(
            "DELETE FROM vectors WHERE id=? AND kind='shared_context'",
            (str(context_id),),
        )
        return cursor.rowcount > 0

    async def update_shared_context(self, context_id: str, updates: dict) -> bool:
        sets = []
        params = []
        for key in ("content", "scope", "importance"):
            if key in updates:
                sets.append(f"{key}=?")
                params.append(updates[key])
        if not sets:
            return False
        sets.append("embedding=NULL")  # force re-embed if content changed
        params.append(str(context_id))
        cursor = self._db.execute(
            f"UPDATE vectors SET {', '.join(sets)} WHERE id=? AND kind='shared_context'",
            params,
        )
        if cursor.rowcount > 0:
            if "content" in updates:
                asyncio.ensure_future(
                    self._embed_and_store(str(context_id), str(updates["content"]))
                )
            return True
        return False

    async def list_shared_context(self, limit: int = 200) -> list[dict]:
        rows = self._db.execute(
            "SELECT id, content, scope, importance, timestamp, metadata FROM vectors WHERE kind='shared_context' ORDER BY importance DESC, created_at DESC LIMIT ?",
            (limit,),
        ).fetchall()
        result = []
        for row in rows:
            entry = {
                "id": row["id"],
                "content": row["content"],
                "scope": row["scope"],
                "importance": row["importance"],
                "timestamp": row["timestamp"],
            }
            try:
                meta = json.loads(row["metadata"] or "{}")
                entry.update(meta)
            except Exception:
                pass
            result.append(entry)
        return result

    async def get_relevant_shared_context(
        self,
        user_id: str = "",
        guild_id: str = "",
        channel_id: str = "",
        is_dm: bool = False,
        is_admin: bool = False,
        max_items: int = 10,
    ) -> list[dict]:
        """Return shared context entries relevant to the current context.

        Filters by scope (user/channel/guild/global) and returns the most
        important entries. With RAG, this could also do semantic search
        but we keep scope-based filtering for shared context since it's
        already structured.
        """
        scopes = ["global"]
        if guild_id:
            scopes.append(f"guild:{guild_id}")
        if channel_id:
            scopes.append(f"channel:{channel_id}")
        if user_id:
            scopes.append(f"user:{user_id}")
        if is_dm and user_id:
            scopes.append(f"dm:{user_id}")

        placeholders = ",".join("?" * len(scopes))
        rows = self._db.execute(
            f"SELECT id, content, scope, importance, timestamp, metadata FROM vectors WHERE kind='shared_context' AND scope IN ({placeholders}) ORDER BY importance DESC, created_at DESC LIMIT ?",
            (*scopes, max_items * 2),
        ).fetchall()

        result = []
        for row in rows:
            entry = {
                "id": row["id"],
                "content": row["content"],
                "scope": row["scope"],
                "importance": row["importance"],
                "timestamp": row["timestamp"],
            }
            try:
                meta = json.loads(row["metadata"] or "{}")
                entry.update(meta)
            except Exception:
                pass
            result.append(entry)

        # Filter DM-to-admin-only
        if not is_admin:
            result = [
                e
                for e in result
                if not str(e.get("scope", "")).startswith("dm:")
                or str(e.get("scope", "")) == f"dm:{user_id}"
            ]

        return result[:max_items]

    # ─── RAG search (new) ─────────────────────────────────────────

    async def rag_search(
        self,
        query: str,
        kinds: list[str] | None = None,
        channel_id: str = "",
        top_k: int = 10,
        min_similarity: float = SIM_THRESHOLD,
    ) -> list[dict]:
        """Semantic search across the vector store.

        Args:
            query: search text
            kinds: filter by kind ('message', 'ltm', 'shared_context')
            channel_id: filter messages by channel
            top_k: max results
            min_similarity: cosine similarity cutoff

        Returns list of dicts with: id, kind, content, author, channel_id,
            timestamp, similarity, metadata
        """
        query_vec = await self._embed(query)
        if query_vec is None:
            return []

        # Build query
        where_parts = ["embedding IS NOT NULL"]
        params = []
        if kinds:
            placeholders = ",".join("?" * len(kinds))
            where_parts.append(f"kind IN ({placeholders})")
            params.extend(kinds)
        if channel_id:
            where_parts.append("(channel_id=? OR channel_id='')")
            params.append(str(channel_id))

        where_clause = " AND ".join(where_parts)
        rows = self._db.execute(
            f"SELECT id, kind, channel_id, author, author_id, content, embedding, metadata, scope, importance, timestamp FROM vectors WHERE {where_clause}",
            params,
        ).fetchall()

        if not rows:
            return []

        # Compute cosine similarity for all rows
        results = []
        query_norm = query_vec / (np.linalg.norm(query_vec) + 1e-8)
        for row in rows:
            blob = row["embedding"]
            if not blob:
                continue
            try:
                vec = _blob_to_embedding(blob)
                if len(vec) != EMBED_DIM:
                    continue
                vec_norm = vec / (np.linalg.norm(vec) + 1e-8)
                sim = float(np.dot(query_norm, vec_norm))
                if sim >= min_similarity:
                    entry = {
                        "id": row["id"],
                        "kind": row["kind"],
                        "channel_id": row["channel_id"],
                        "author": row["author"],
                        "author_id": row["author_id"],
                        "content": row["content"],
                        "scope": row["scope"],
                        "importance": row["importance"],
                        "timestamp": row["timestamp"],
                        "similarity": sim,
                    }
                    try:
                        meta = json.loads(row["metadata"] or "{}")
                        entry.update(meta)
                    except Exception:
                        pass
                    results.append(entry)
            except Exception:
                continue

        # Sort by similarity descending, take top_k
        results.sort(key=lambda x: x["similarity"], reverse=True)
        return results[:top_k]

    async def rag_relevant_context(
        self,
        query: str,
        channel_id: str = "",
        top_k: int = 15,
    ) -> list[dict]:
        """Get semantically relevant context for a user message.

        Searches across messages, LTM, and shared context. Returns a
        mixed list of the most semantically relevant entries, useful
        for augmenting the system prompt with RAG context.
        """
        results = await self.rag_search(
            query,
            kinds=["message", "ltm", "shared_context"],
            channel_id=channel_id,
            top_k=top_k * 3,  # over-fetch then dedupe/diversify
        )

        # Deduplicate by content similarity (avoid returning near-identical messages)
        seen = set()
        deduped = []
        for r in results:
            key = r["content"][:200].lower()
            if key not in seen:
                seen.add(key)
                deduped.append(r)

        # Diversify: ensure we get a mix of kinds
        by_kind = {"message": [], "ltm": [], "shared_context": []}
        for r in deduped:
            by_kind.setdefault(r["kind"], []).append(r)

        mixed = []
        # Prioritize LTM and shared_context (durable facts) then messages
        for kind in ("ltm", "shared_context", "message"):
            mixed.extend(by_kind.get(kind, [])[: top_k // 2])

        return mixed[:top_k]

    # ─── lifecycle ────────────────────────────────────────────────

    async def flush(self):
        """No-op — SQLite is autocommit. Kept for interface compat."""
        pass

    def load_from_disk(self):
        """No-op — DB is loaded in __init__. Kept for interface compat."""
        pass